on: [push]

jobs:
  test_npm_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install
        uses: actions/setup-node@v1
      - uses: uxland/actions/ci/npm@master
